"""add language to posts

Revision ID: 91563e32750b
Revises: f328db487286
Create Date: 2020-10-31 15:03:52.376211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91563e32750b'
down_revision = 'f328db487286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
